#!/bin/bash

echo "Restarting HN ..."
killall haskellnews -q

while true
do
    if ps -C haskellnews > /dev/null
    then
       echo Waiting...;
    else
       break;
    fi
done

/home/chris/.local/bin/haskellnews haskellnews.conf 2> /dev/null & disown
